[test]
preload = [
  "./test/happydom.ts",
  "./packages/react/test/testing-library.ts"
]
exclude = ["e2e/**", "packages/*/dist/**"]

[coverage]
include = ["packages/**/*.ts", "packages/**/*.tsx"]
exclude = ["**/__tests__/**", "**/test/**", "**/dist/**"]