[install]
linker = "isolated"
registry = "https://mirrors.cloud.tencent.com/npm/"

[test]
root = "packages"
preload = [
  "./test/happydom.ts",
  "./test/testing-library.ts"
]

[coverage]
include = ["packages/**/*.ts", "packages/**/*.tsx"]
exclude = ["**/__tests__/**", "**/test/**", "**/dist/**"]