import { create } from "zustand";
import { persist, type StorageValue } from "zustand/middleware";

const getStorageByType = (type: string): Storage => {
  if (typeof window === "undefined") {
    throw new Error("Storage only available in browser environment");
  }
  return type === "local" ? localStorage : sessionStorage;
};

let type = "local";
const getStorage = (): Storage => getStorageByType(type);

export interface SaveSlot {
  data: string;
  timestamp: string;
  meta: string;
}

export class Save implements SaveSlot {
  data: string;
  timestamp: string;
  meta: string;

  constructor(data: object) {
    this.data = JSON.stringify(data);
    this.timestamp = new Intl.DateTimeFormat(undefined, {
      month: "short",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    }).format(Date.now());
    this.meta = "autogenerated";
  }
}

interface StorageInterface {
  storage: Map<string, SaveSlot[]>;
  setStorage: (title: string, index: number, data: object) => void;
  changeFormat: (format: string) => void;
}

const useStorage = create<StorageInterface>()(
  persist(
    (set, get) => ({
      storage: new Map(),
      setStorage: (title, index, data) => {
        const newSavesMap = new Map(get().storage);
        const file_saves = [...(newSavesMap.get(title) || [])];
        file_saves[index] = new Save(data);
        newSavesMap.set(title, file_saves);
        set({ storage: newSavesMap });
      },
      changeFormat: (format) => {
        type = format;
      },
    }),
    {
      name: "inkStory",
      storage: {
        getItem: (name) => {
          const str = getStorage().getItem(name);
          if (!str) return null;
          try {
            const { state } = JSON.parse(str);
            return {
              state: {
                ...state,
                storage: new Map(state.storage),
              },
            };
          } catch (e) {
            console.error("InkWeave: Failed to parse storage data:", e);
            return null;
          }
        },
        setItem: (name, newValue: StorageValue<StorageInterface>) => {
          const str = JSON.stringify({
            state: {
              ...newValue.state,
              storage: Array.from(newValue.state.storage.entries()),
            },
          });
          getStorage().setItem(name, str);
        },
        removeItem: (name) => {
          getStorage().removeItem(name);
        },
      },
    },
  ),
);

export default useStorage;
